name: Dump
description: |
  dump all the context variables

inputs:
  enable-context:
    default: "true"
    required: false
    description: "enable context dump"
  print-env:
    default: "true"
    required: false
    description: "print env variables"

outputs:
  dumped-date:
    value: ${{steps.current.outputs.date}}

runs:
  using: composite
  steps:
    - run: printenv | sort
      shell: bash
      if: ${{inputs.print-env == 'true'}}

    - run: echo "${CONTEXT}"
      if: ${{inputs.enable-context == 'true'}}
      env:
        CONTEXT: ${{ toJson(github) }}
      shell: bash
      
    - run: echo "{CONTEXT}"
      shell: bash

    - id: current
      run: echo date=$(date) >> ${GITHUB_OUTPUT}
      shell: bash
